

POST https://localhost:7041/api/orders 
Content-Type: application/json

{
  "lines":
  [
    {
      "ProductId": 1,
      "Quantity": 2
    },
    {
      "ProductId": 2,
      "Quantity": 1
    }
  ]
}

### ProductOutOfStockException

POST https://localhost:7041/api/orders 
Content-Type: application/json

{
  "lines":
  [
    {
      "ProductId": 21,
      "Quantity": 999
    }
  ]
}


### Empty Lines
POST https://localhost:7041/api/orders 
Content-Type: application/json

{
  "lines": [ ]
}



### Bad Product Id and Quantity
POST https://localhost:7041/api/orders 
Content-Type: application/json

{
  "lines":
  [
    {
      "ProductId": 0,
      "Quantity": -1
    }
  ]
}
