@host = https://localhost:7001
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJtaWNyb3NlcnZpY2VzIiwiaXNzIjoiaWRlbnRpdHktc2VydmljZSIsImV4cCI6MTc4MzAwMDg5OSwic3ViIjoiam9obiIsIm5hbWUiOiJqb2huIiwicGhvbmUiOiIrMTIzNDU2Nzg5MCIsImlhdCI6MTc4MzAwMDU5OSwibmJmIjoxNzgzMDAwNTk5fQ.uQ1gYdSSEQv5uqNH8Su0Kmbvh0RNbtbZE9CE6eroBNM

POST {{host}}/api/orders 
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "lines":
  [
    {
      "ProductId": 1,
      "Quantity": 3
    },
    {
      "ProductId": 2,
      "Quantity": 1
    }
  ]
}

### ProductOutOfStockException

POST {{host}}/api/orders 
Content-Type: application/json

{
  "lines":
  [
    {
      "ProductId": 21,
      "Quantity": 999
    }
  ]
}


### Empty Lines
POST {{host}}/api/orders 
Content-Type: application/json

{
  "lines": [ ]
}



### Bad Product Id and Quantity
POST {{host}}/api/orders 
Content-Type: application/json

{
  "lines":
  [
    {
      "ProductId": 0,
      "Quantity": -1
    }
  ]
}
