@host = https://localhost:7001
@access_token = your_ascess_token

POST {{host}}/api/orders 
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "lines":
  [
    {
      "ProductId": 1,
      "Quantity": 3
    },
    {
      "ProductId": 2,
      "Quantity": 1
    }
  ]
}

### ProductOutOfStockException

POST {{host}}/api/orders 
Content-Type: application/json

{
  "lines":
  [
    {
      "ProductId": 21,
      "Quantity": 999
    }
  ]
}


### Empty Lines
POST {{host}}/api/orders 
Content-Type: application/json

{
  "lines": [ ]
}



### Bad Product Id and Quantity
POST {{host}}/api/orders 
Content-Type: application/json

{
  "lines":
  [
    {
      "ProductId": 0,
      "Quantity": -1
    }
  ]
}
