
@host = https://localhost:7031

POST {{host}}/api/cart HTTP/1.1
Content-Type: application/json

{
  "productId": 3,
  "quantity": 1
}

### 

POST {{host}}/api/cart HTTP/1.1
Content-Type: application/json

{
  "productId": 3,
  "quantity": -1
}


###

POST {{host}}/api/cart/checkout HTTP/1.1


###